module.exports = {
  content: [
    './index.html',
    './App.tsx',
    './index.tsx',
    './constants.tsx',
    './types.ts',
    './apps/**/*.{ts,tsx,js,jsx}',
    './components/**/*.{ts,tsx,js,jsx}',
    './context/**/*.{ts,tsx,js,jsx}',
    './hooks/**/*.{ts,tsx,js,jsx}',
    './utils/**/*.{ts,tsx,js,jsx}',
  ],
  safelist: [
    'space-y-1',
    'space-y-2',
    'space-y-4',
    'bg-green-700',
    'bg-violet-700',
    'bg-violet-800',
    'bg-violet-900',
    'bg-amber-800',
    'bg-amber-900',
    'bg-amber-950',
    'bg-red-700',
    'text-green-500',
    'text-yellow-500',
    'text-orange-500',
    'text-red-500',
    'text-purple-600',
    'text-pink-500',
    'text-gray-400',
    'text-red-600',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--app-font)', 'sans-serif'],
        display: ['var(--font-display)', 'serif'],
        label: ['var(--font-label)', 'monospace'],
      },
      colors: {
        primary: 'hsl(var(--primary-hue), var(--primary-sat), var(--primary-lightness))',
        'primary-focus': 'hsl(var(--primary-hue), var(--primary-sat), calc(var(--primary-lightness) - 10%))',
        'primary-light': 'hsl(var(--primary-hue), var(--primary-sat), 92%)',
        surface: 'rgba(255, 255, 255, 0.75)',
        'surface-glass': 'rgba(255, 255, 255, 0.35)',
        ink: '#2b2933',
        'ink-soft': '#8b8996',
      },
      animation: {
        'fade-in': 'fadeIn 0.35s cubic-bezier(0.4, 0, 0.2, 1)',
        'slide-up': 'slideUp 0.35s cubic-bezier(0.25, 1, 0.5, 1)',
        'slide-down': 'slideDown 0.35s cubic-bezier(0.25, 1, 0.5, 1)',
        'pop-in': 'popIn 0.35s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
        'deal-in': 'dealIn 0.5s cubic-bezier(0.22, 1, 0.36, 1) both',
        'float-up': 'floatUp 3s ease-out forwards',
        wiggle: 'wiggle 0.5s ease-in-out infinite',
        'bounce-slow': 'bounceSlow 2s ease-in-out infinite',
        float: 'floatDrift 4s ease-in-out infinite alternate',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
        shimmer: 'shimmer 2.5s ease-in-out infinite',
        'dot-pulse': 'dotPulse 1.2s ease-in-out infinite',
        breathe: 'breathe 5s ease-in-out infinite',
        'drift-slow': 'driftSlow 18s ease-in-out infinite alternate',
        'drift-slower': 'driftSlow 26s ease-in-out infinite alternate-reverse',
        sway: 'sway 6s ease-in-out infinite alternate',
        'rise-in': 'riseIn 0.5s cubic-bezier(0.22, 1, 0.36, 1) both',
        'tarot-shine': 'tarotShine 1.05s ease-out',
        'tarot-glow': 'tarotGlow 3.6s ease-in-out infinite',
        'tarot-bob': 'tarotBob 4.8s ease-in-out infinite',
        'tarot-sheen': 'tarotSheen 3.2s ease-in-out infinite',
        'tarot-twinkle': 'tarotTwinkle 2.4s ease-in-out infinite',
        'tarot-float': 'tarotFloat 5.5s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'scale(0.97) translateY(4px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        popIn: {
          '0%': { opacity: '0', transform: 'scale(0.5)' },
          '60%': { transform: 'scale(1.05)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        dealIn: {
          '0%': { opacity: '0', transform: 'translateY(46px) scale(0.62) rotate(-9deg)' },
          '65%': { opacity: '1', transform: 'translateY(-4px) scale(1.04) rotate(2deg)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1) rotate(0)' },
        },
        floatUp: {
          '0%': { opacity: '1', transform: 'translateY(100vh) scale(1)' },
          '50%': { opacity: '1' },
          '100%': { opacity: '0', transform: 'translateY(-50px) scale(1.5)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'translate(-50%, -100%) rotate(-3deg)' },
          '50%': { transform: 'translate(-50%, -100%) rotate(3deg)' },
        },
        bounceSlow: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        floatDrift: {
          '0%': { transform: 'translateY(0) scale(1)', opacity: '0.3' },
          '100%': { transform: 'translateY(-30px) scale(1.1)', opacity: '0.6' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 15px rgba(139, 92, 246, 0.15)' },
          '50%': { boxShadow: '0 0 25px rgba(139, 92, 246, 0.3)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        dotPulse: {
          '0%, 80%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '40%': { opacity: '1', transform: 'scale(1.1)' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.55' },
          '50%': { transform: 'scale(1.06)', opacity: '0.85' },
        },
        driftSlow: {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '100%': { transform: 'translate(28px, -22px) scale(1.12)' },
        },
        sway: {
          '0%': { transform: 'rotate(-2.2deg)' },
          '100%': { transform: 'rotate(2.2deg)' },
        },
        riseIn: {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        tarotShine: {
          '0%': { transform: 'translateX(-130%) skewX(-12deg)', opacity: '0' },
          '12%': { opacity: '0.85' },
          '60%, 100%': { transform: 'translateX(230%) skewX(-12deg)', opacity: '0' },
        },
        tarotGlow: {
          '0%, 100%': { opacity: '0.3', transform: 'scale(0.94)' },
          '50%': { opacity: '0.68', transform: 'scale(1.05)' },
        },
        tarotBob: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        tarotSheen: {
          '0%': { transform: 'translateX(-130%) skewX(-14deg)', opacity: '0' },
          '18%': { opacity: '0.55' },
          '50%, 100%': { transform: 'translateX(240%) skewX(-14deg)', opacity: '0' },
        },
        tarotTwinkle: {
          '0%, 100%': { opacity: '0.15', transform: 'scale(0.7)' },
          '50%': { opacity: '0.9', transform: 'scale(1.15)' },
        },
        tarotFloat: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
    },
  },
};
